name: Validate the renovate configuration

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/renovate.json5'

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate
        uses: rinchsan/renovate-config-validator@v0.0.11
        with:
          pattern: '*.json5'
